package rpc.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.7
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoRPC", targetNamespace = "http://demo.rpc")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoRPC_PortType {


    /**
     * 
     * @param person
     * @return
     *     returns rpc.demo.Person
     */
    @WebMethod
    @WebResult(name = "demoPersonReturn", targetNamespace = "")
    @RequestWrapper(localName = "demoPerson", targetNamespace = "http://demo.rpc", className = "rpc.demo.DemoPerson")
    @ResponseWrapper(localName = "demoPersonResponse", targetNamespace = "http://demo.rpc", className = "rpc.demo.DemoPersonResponse")
    public Person demoPerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

}
