package rpc.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.7
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DemoRPC", targetNamespace = "http://demo.rpc", wsdlLocation = "/WEB-INF/wsdl/DemoRPC.wsdl")
public class DemoRPC_Service
    extends Service
{

    private static String overriddenURLAddress = null;

    private static final URL DEMORPC_WSDL_LOCATION;
    private static final WebServiceException DEMORPC_EXCEPTION;
    private static final QName DEMORPC_QNAME = new QName("http://demo.rpc", "DemoRPC");

    static {
        DEMORPC_WSDL_LOCATION = rpc.demo.DemoRPC_Service.class.getResource("/WEB-INF/wsdl/DemoRPC.wsdl");
        WebServiceException e = null;
        if (DEMORPC_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/WEB-INF/wsdl/DemoRPC.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        DEMORPC_EXCEPTION = e;
    }

    public DemoRPC_Service() {
        super(__getWsdlLocation(), DEMORPC_QNAME);
    }

    public DemoRPC_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEMORPC_QNAME, features);
    }

    public DemoRPC_Service(URL wsdlLocation) {
        super(wsdlLocation, DEMORPC_QNAME);
    }

    public DemoRPC_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEMORPC_QNAME, features);
    }

    public DemoRPC_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoRPC_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DemoRPC
     */
    @WebEndpoint(name = "DemoRPC")
    public DemoRPC_PortType getDemoRPC() {
        return super.getPort(new QName("http://demo.rpc", "DemoRPC"), DemoRPC_PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoRPC
     */
    @WebEndpoint(name = "DemoRPC")
    public DemoRPC_PortType getDemoRPC(WebServiceFeature... features) {
        return super.getPort(new QName("http://demo.rpc", "DemoRPC"), DemoRPC_PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMORPC_EXCEPTION!= null) {
            throw DEMORPC_EXCEPTION;
        }
        return DEMORPC_WSDL_LOCATION;
    }

    // Use to get a proxy class for demoRPC
    private final java.lang.String demoRPC_address = "rhel9-base.gym.lan:9081/DemoRPC/services/DemoRPC";

    public String getDemoRPCAddresses() {
        if (overriddenURLAddress == null) {
            overriddenURLAddress = System.getProperty("overriddenURLAddress");
            if (overriddenURLAddress == null) {
                overriddenURLAddress = "http://rhel9-base.gym.lan:9081/DemoRPC/services/DemoRPC";
            }
        }
        return overriddenURLAddress;
    }

    private java.lang.String demoRPCPortName = "DemoRPC";

    // The WSDD port name defaults to the port name.
    private java.lang.String demoRPCWSDDPortName = "DemoRPC";

    public java.lang.String getDemoRPCWSDDPortName() {
        return demoRPCWSDDPortName;
    }

    public void setDemoRPCWSDDPortName(java.lang.String name) {
        demoRPCWSDDPortName = name;
    }

    public DemoRPC_PortType getDemoRPC(URL portAddress) {
        DemoRPC_PortType port = null;
        DemoRPC_Service jaxwsService = null;

        if (portAddress == null) {
            return getDemoRPC();
        } else {
            String portAddressFile = portAddress.getFile();
            if (portAddressFile.endsWith("?wsdl")) {
                jaxwsService = new DemoRPC_Service(portAddress);
            } else {
                String wsdlURLString = portAddressFile + "?wsdl";
                try {
                    URL wsdlURL = new URL(portAddress.getProtocol(), portAddress.getHost(), portAddress.getPort(), wsdlURLString);
                    jaxwsService = new DemoRPC_Service(wsdlURL);
                } catch (MalformedURLException e) {
                    return getDemoRPC();
                }
            }
        }

        if (jaxwsService != null) {
            port = jaxwsService.getDemoRPC();
        }

        if (port == null) {
            port = getDemoRPC();
        }

        return port;
    }

    public void setPortNamePrefix(java.lang.String prefix) {
        demoRPCWSDDPortName = prefix + "/" + demoRPCPortName;
    }

    private java.util.Map port2NamespaceMap = null;

    protected synchronized java.util.Map getPort2NamespaceMap() {
        if (port2NamespaceMap == null) {
            port2NamespaceMap = new java.util.HashMap();
            port2NamespaceMap.put(
               "DemoRPC",
               "http://schemas.xmlsoap.org/wsdl/soap/");
        }
        return port2NamespaceMap;
    }

    private java.util.HashSet ports = null;

}
